### ISSUE TITLE
Async text fields in prompts throw DiscordAPIError: Cannot send an empty message

### ISSUE THREAD

**Issue by BadCoder1337** [1Computer1/discord-akairo#38]
```js
(node:18356) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send an empty message
    at RequestHandler.execute (D:\Projects\backend\packages\streams\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
```js
{
    id: 'id',
    type: 'string'
    prompt: {
        start: async () => `some text: ${await promise}`,
    },
}
```

**Comment by 1Computer1** [comment]
This is actually not supported in this first place, but it probably will be now that you've pointed it out.

**Comment by 1Computer1** [comment]
Done!

**Comment by BadCoder1337** [comment]
Great! Thanks
