### ISSUE TITLE
Prompting with custom type

### ISSUE THREAD

**Issue by williamokano** [1Computer1/discord-akairo#49]
Prompting is not working with custom type.

I'm just playing around to test some stuff and as I couldn't find how to validate prompts I thought that custom types might be my solution.

My custom type is just a e-mail validation, so I have the following command

```js
const { Command } = require('discord-akairo')

function isValidEmail(word) {
    if (word.startsWith('william'))
        return word
    return null
}

module.exports = class RegisterCommand extends Command {
    constructor() {
        super('register', {
            aliases: ['register'],
            args: [
                {
                    id: 'email',
                    type: word => {
                        return isValidEmail(word)
                    },
                    prompt: {
                        start: 'Please enter your e-mail',
                        retry: 'LOL! Try again!'
                    }
                }
            ]
        })
    }

    exec(message, args) {
        return message.reply('Reply with ```' + JSON.stringify(args) + '```')
    }
}
```

The intended behavior is: ask for e-mail (with prompt) and when the user inputs the value, I "execute" the type to check wether the value is valid or not, returning a `null` if something wrong.

What is happening: prompt is not happening.

Version: 
discord-akairo => 7.5.5
discord.js => 11.4.2

**Comment by BlackMix** [comment]
U need use Flag option

**Comment by williamokano** [comment]
@BlackMix I'm not quite sure how to do that, could you give me an example, please?

**Comment by BlackMix** [comment]
```
const { Command, Flag } = require('discord-akairo')

function isValidEmail(word) {
    return false ? Flag.fail('Email false') : word
}

module.exports = class PingCommand extends Command {
    constructor() {
        super('register', {
            aliases: ['register'],
            args: [
                {
                    id: 'email',
                    type: word => {
                        return isValidEmail(word)
                    },
                    prompt: {
                        start: 'Please enter your e-mail',
                        retry: 'LOL! Try again!'
                    }
                }
            ]
        })
    }

    exec(message, args) {
        return message.reply('Reply with ```' + JSON.stringify(args) + '```')
    }
}
```

**Comment by williamokano** [comment]
Sorry, I tried as you showed me and I got the following error:

```bash
!(node:18918) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fail' of undefined
    at isValidEmail (/Users/william/Workspace/zaque-bot/src/commands/registerCommand.js:4:17)
    at RegisterCommand.type (/Users/william/Workspace/zaque-bot/src/commands/registerCommand.js:15:32)
    at Argument._processType (/Users/william/Workspace/zaque-bot/node_modules/discord-akairo/src/struct/Argument.js:283:35)
    at Argument.cast (/Users/william/Workspace/zaque-bot/node_modules/discord-akairo/src/struct/Argument.js:248:26)
```

My validation is the following:

```js
const { Command, Flag } = require('discord-akairo')

function isValidEmail(word) {
    return Flag.fail('not valid input')
}
```

**Comment by BlackMix** [comment]
I think, type: word => {

type: (message, word) => {
^ this correct

**Comment by BlackMix** [comment]
U need install master version, maybe your is old in npm

**Comment by williamokano** [comment]
Let me try this. I'm using the latest stable version (7.5.5). Gonna try with the 8.0.0-BETA3 also

**Comment by williamokano** [comment]
Just found where my problem was (I guess). I was not returning `null`, I was returning false. The code works just fine. @BlackMix thanks the time and sorry for wasting it with noob questions.
